global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:9091"]

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:9092"]

  - job_name: "todo-service"
    static_configs:
      - targets: ["todo-service:9093"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]